version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000/graphql
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development # 開発環境用のターゲット
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development # 開発環境指定
      # SQLiteを使用するので、以下は不要
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=questionnaire_db
    networks:
      - app-network

  # 開発時はコメントアウト可能
  # db:
  #   image: mysql:8.0
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=questionnaire_db
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
